apiVersion: v1
kind: Service
metadata:
  labels:
    app: jbma-demo-cache
  name: jbma-demo-cache
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: jbma-demo-cache
  type: ClusterIP