apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: jbma-db3
  name: jbma-db3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbma-db3
  template:
    metadata:
      labels:
        app: jbma-db3
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: database-secret-jbma-db3
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: database-secret-jbma-db3
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: database-secret-jbma-db3
        image: bitnami/postgresql:17.5.0
        name: jbma-db3
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: jbma-db3-pvc
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: jbma-db3-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi