apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: jbma-demo-db
  name: jbma-demo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jbma-demo-db
  template:
    metadata:
      labels:
        app: jbma-demo-db
    spec:
      containers:
      - env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: DATABASE_USER
              name: database-secret-jbma-demo-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DATABASE_PASSWORD
              name: database-secret-jbma-demo-db
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: database-secret-jbma-demo-db
        image: bitnami/postgresql:17.5.0
        name: jbma-demo-db
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /bitnami/postgresql
          name: jbma-demo-db-pvc
      securityContext:
        fsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: jbma-demo-db-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi